#!/usr/bin/env bash
#
# generate-changelog.sh
#
# Generated by the smp-github Claude Code plugin.
# https://github.com/saturdaymp/claude-skills
#
# Generates a CHANGELOG.md from GitHub releases using the GitHub CLI (gh).
# The release body content is preserved as-is from each GitHub release.
#
# Usage: ./scripts/generate-changelog.sh [output-path]
#
# Arguments:
#   output-path  Path to the output file (default: CHANGELOG.md in the repo root)
#
# Requirements:
#   - git
#   - GitHub CLI (gh) installed and authenticated
#

set -euo pipefail

# --- Configuration ---
OUTPUT_FILE="${1:-CHANGELOG.md}"

# --- Preflight checks ---
if ! command -v gh &> /dev/null; then
  echo "Error: GitHub CLI (gh) is not installed. Install it from https://cli.github.com/" >&2
  exit 1
fi

if ! gh auth status &> /dev/null; then
  echo "Error: GitHub CLI is not authenticated. Run 'gh auth login' first." >&2
  exit 1
fi

if ! git rev-parse --is-inside-work-tree &> /dev/null; then
  echo "Error: Not inside a git repository." >&2
  exit 1
fi

# --- Detect repository ---
REPO=$(gh repo view --json nameWithOwner --jq '.nameWithOwner')
if [[ -z "$REPO" ]]; then
  echo "Error: Could not determine GitHub repository." >&2
  exit 1
fi

# --- Fetch releases ---
RELEASES=$(gh release list --repo "$REPO" --limit 1000 --json tagName,publishedAt,isDraft,isPrerelease --jq '[.[] | select(.isDraft == false)] | sort_by(.publishedAt) | reverse')

RELEASE_COUNT=$(echo "$RELEASES" | jq 'length')
if [[ "$RELEASE_COUNT" -eq 0 ]]; then
  echo "No published releases found for $REPO."
  exit 0
fi

echo "Found $RELEASE_COUNT release(s) for $REPO"

# --- Build changelog ---
{
  echo "# Changelog"
  echo ""
  echo "All notable changes to this project will be documented in this file."
  echo "This file is auto-generated from [GitHub releases](https://github.com/$REPO/releases)."
  echo ""

  # Collect link references
  LINK_REFS=""

  for i in $(seq 0 $((RELEASE_COUNT - 1))); do
    TAG=$(echo "$RELEASES" | jq -r ".[$i].tagName")
    IS_PRERELEASE=$(echo "$RELEASES" | jq -r ".[$i].isPrerelease")

    # Fetch full release details
    RELEASE_DETAIL=$(gh release view "$TAG" --repo "$REPO" --json tagName,name,body,publishedAt,isPrerelease)

    NAME=$(echo "$RELEASE_DETAIL" | jq -r '.name // empty')
    BODY=$(echo "$RELEASE_DETAIL" | jq -r '.body // empty')
    PUBLISHED=$(echo "$RELEASE_DETAIL" | jq -r '.publishedAt')

    # Format the date as YYYY-MM-DD
    DATE=$(date -jf "%Y-%m-%dT%H:%M:%SZ" "$PUBLISHED" "+%Y-%m-%d" 2>/dev/null || echo "$PUBLISHED" | cut -c1-10)

    # Strip leading 'v' for the display version
    VERSION="${TAG#v}"

    # Build the heading
    HEADING="## [$VERSION] - $DATE"
    if [[ "$IS_PRERELEASE" == "true" ]]; then
      HEADING="$HEADING (Pre-release)"
    fi

    echo "$HEADING"
    echo ""

    if [[ -n "$BODY" ]]; then
      echo "$BODY"
      echo ""
    fi

    # Collect link reference
    LINK_REFS="${LINK_REFS}[$VERSION]: https://github.com/$REPO/releases/tag/$TAG
"
  done

  # Write link references
  echo "$LINK_REFS"
} > "$OUTPUT_FILE"

echo "Changelog written to $OUTPUT_FILE"
